// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Pagination: typeof import('./components/Pagination.vue')['default']
    'TableConfigure.ce': typeof import('./components/TableConfigure.ce.vue')['default']
    'TableV2.ce': typeof import('./components/TableV2.ce.vue')['default']
  }
}

export {}
